apiVersion: v1
kind: Secret
metadata:
  name: my-deploy
  namespace: argocd
type: Opaque
data:
  privateKey: X
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
stringData:
  slack-token: <slack-token>
