# Reference: https://cert-manager.io/docs/usage/certificate/
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <MY_APP>-cert
  namespace: istio-system
spec:
  secretName: <MY_APP>-tls-secret
  dnsNames:
    - <MY_APP>-local.<MY_DOMAIN>  # Change this to your domain
  issuerRef:
    name: tls-ca-issuer
    kind: ClusterIssuer
